"use client";

import { SessionProvider } from 'next-auth/react';
import './globals.css'
import { Inter, Figtree, Lato, DM_Serif_Display, Montserrat} from 'next/font/google'
import { QueryClient, QueryClientProvider } from 'react-query';
import '@fortawesome/fontawesome-svg-core/styles.css';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Uniben Online Market',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <SessionProvider>
        <html lang="en">
          <head>
            <title>
                Uniben Online Market
            </title>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
            <link href="https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;500;600;700;800;900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Satisfy&display=swap" rel="stylesheet"/>
          </head>
          <body className={inter.className}>{children}</body>
        </html>      
      </SessionProvider>
    </QueryClientProvider>

  )
}
