"use client";

import { SessionProvider } from 'next-auth/react';
import './globals.css'
import { Inter, Figtree, Lato, DM_Serif_Display, Montserrat} from 'next/font/google'
import { QueryClient, QueryClientProvider } from 'react-query';
import '@fortawesome/fontawesome-svg-core/styles.css';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Uniben Online Market',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <SessionProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>      
      </SessionProvider>
    </QueryClientProvider>

  )
}
