"use client";

import { SessionProvider } from 'next-auth/react';
import './globals.css'
import { QueryClient, QueryClientProvider } from 'react-query';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Chart from 'chart.js/auto'
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader

// export const metadata = {
//   title: 'Uniben Online Market',
//   description: 'Generated by create next app',
// }
import { Figtree, Montserrat, DM_Serif_Display, Lato } from 'next/font/google'
 
const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-figtree',
})
 
const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const lato = Lato({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato',
  weight: ['100', '300', '400', '700']
})

export default function RootLayout({ children }) {

  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <SessionProvider>
        <html lang="en" className={`${montserrat.variable} ${lato.variable} ${figtree.variable}`} >
          <head>
            <title>
                Uniben Online Market
            </title>
          </head>
          <body>{children}</body>
        </html>      
      </SessionProvider>
    </QueryClientProvider>

  )
}
